#pragma once

#include "stdafx.h"
#include "stdio.h"

enum MenuID : int
{
	CustomizeCategory_Parts = 0x801,
	CustomizeCategory_Performance,
	CustomizeCategory_Visual,
	Customize_Parts_Bodykits = 0x101,
	Customize_Parts_Spoilers,
	Customize_Parts_Rims,
	Customize_Parts_Hoods,
	Customize_Parts_RoofScoops,
	Customize_Parts_Interior,
	Customize_Parts_Roof,
	Customize_Parts_Brakes,
	Customize_Parts_Headlights,
	Customize_Parts_Taillights,
	Customize_Parts_Mirrors,
	Customize_Parts_Attachments,
	Customize_Parts_Attachment0,
	Customize_Parts_Attachment1,
	Customize_Parts_Attachment2,
	Customize_Parts_Attachment3,
	Customize_Parts_Attachment4,
	Customize_Parts_Attachment5,
	Customize_Parts_Attachment6,
	Customize_Parts_Attachment7,
	Customize_Parts_Attachment8,
	Customize_Parts_Attachment9,
	Customize_Performance_Engine = 0x201,
	Customize_Performance_Transmission,
	Customize_Performance_Chassis,
	Customize_Performance_Nitrous,
	Customize_Performance_Tires,
	Customize_Performance_Brakes,
	Customize_Performance_Induction,
	Customize_Visual_Paint = 0x301,
	Customize_Visual_Vinyls,
	Customize_Visual_RimPaint,
	Customize_Visual_WindowTint,
	Customize_Visual_Decals,
	Customize_Visual_Numbers,
	Customize_Visual_CustomGauges,
	Customize_Visual_Driver,
	Customize_Visual_LicensePlate,
	Customize_Visual_Tires = 0x314,
	Customize_Visual_Neon,
	Customize_Decals_Windshield = 0x501,
	Customize_Decals_RearWindow,
	Customize_Decals_LeftDoor,
	Customize_Decals_RightDoor,
	Customize_Decals_LeftQuarter,
	Customize_Decals_RightQuarter,
	Customize_Decals_Slot1 = 0x601,
	Customize_Decals_Slot2,
	Customize_Decals_Slot3,
	Customize_Decals_Slot4,
	Customize_Decals_Slot5,
	Customize_Decals_Slot6,
	Customize_Decals_Slot7,
	Customize_Decals_Slot8,
	Customize_Rims_Min = 0x701,
	Customize_Rims_First = 0x702,
	Customize_Rims_Last = 0x7FF,
	Customize_Vinyls_Min = 0x401,
	Customize_Vinyls_First = 0x402,
	Customize_Vinyls_Last = 0x4FF,
	Customize_Vinyls_DefaultCam = 0x402,
	Customize_Vinyls_AltCam = 0x403,
	Customize_Decals_Slots_Min = 0x600,
	Customize_First = 0x101,
	Customize_Last = 0x8FF,
};